
target :TestsApp, :exclusive => true do
  platform :ios, '5.0'

  pod 'NSStringFromAnyObject'
end

target :TestsCommandLineApp, :exclusive => true do
  platform :osx, '10.7'

  pod 'NSStringFromAnyObject'
end
