
target :TestsApp, :exclusive => true do
  platform :ios, '5.0'

  pod 'NSStringFromAnyObject', :git => 'https://github.com/stanislaw/NSStringFromAnyObject'
end

target :TestsCommandLineApp, :exclusive => true do
  platform :osx, '10.7'

  pod 'NSStringFromAnyObject', :git => 'https://github.com/stanislaw/NSStringFromAnyObject'
end
